import { jsPDF } from "jspdf";
import type { CargoItem, ContainerSpec, LoadingResult } from "@/lib/containerPacking";
import { calculateContainerBalance } from "@/lib/containerBalance";

const IN_TO_CM = 2.54;
const LB_TO_KG = 0.453592;

export interface BasicPackingReportProps {
  containerSpec: ContainerSpec;
  cargoItems: CargoItem[];
  result: LoadingResult;
  totalContainers: number;
  unitSystem: "imperial" | "metric";
  containerPlans?: {
    label: string;
    containerSpec: ContainerSpec;
    result: LoadingResult;
  }[];
  brand?: {
    name?: string;
    domainSuffix?: string;
    tagline?: string;
    logoDataUrl?: string;
    accentColor?: string;
  };
}

function resolveBrand(brand?: BasicPackingReportProps["brand"]) {
  return {
    name: brand?.name?.trim() || "AccessToNorth",
    domainSuffix: brand?.domainSuffix ?? ".com",
    tagline: brand?.tagline ?? "Container loading calculator",
    logoDataUrl: brand?.logoDataUrl,
    accentColor: /^#[0-9a-f]{6}$/i.test(brand?.accentColor ?? "") ? brand!.accentColor! : "#007BFF",
  };
}

function hexToRgb(hex: string): [number, number, number] {
  const value = hex.replace("#", "");
  if (!/^[0-9a-f]{6}$/i.test(value)) return [59, 130, 246];
  return [
    Number.parseInt(value.slice(0, 2), 16),
    Number.parseInt(value.slice(2, 4), 16),
    Number.parseInt(value.slice(4, 6), 16),
  ];
}

function addHeader(doc: jsPDF, title: string, subtitle: string, brandInput?: BasicPackingReportProps["brand"]) {
  const brand = resolveBrand(brandInput);
  const [accentR, accentG, accentB] = hexToRgb(brand.accentColor);
  const pageWidth = doc.internal.pageSize.getWidth();
  doc.setFillColor(255, 255, 255);
  doc.rect(0, 0, pageWidth, 64, "F");
  doc.setDrawColor(226, 232, 240);
  doc.line(0, 64, pageWidth, 64);
  if (brand.logoDataUrl) {
    try {
      const format = brand.logoDataUrl.startsWith("data:image/jpeg") ? "JPEG" : "PNG";
      doc.addImage(brand.logoDataUrl, format, 32, 13, 36, 36);
    } catch {
      doc.setFillColor(accentR, accentG, accentB);
      doc.roundedRect(32, 13, 36, 36, 8, 8, "F");
    }
  } else {
    doc.setFillColor(accentR, accentG, accentB);
    doc.roundedRect(32, 13, 36, 36, 8, 8, "F");
    doc.setDrawColor(255, 255, 255);
    doc.setLineWidth(1.7);
    doc.line(43, 27, 48, 32);
    doc.line(48, 32, 58, 22);
  }
  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text(brand.name, 78, 28);
  const brandWidth = doc.getTextWidth(brand.name);
  doc.setTextColor(accentR, accentG, accentB);
  doc.text(brand.domainSuffix, 78 + brandWidth, 28);
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10);
  doc.text(title, pageWidth - 32, 25, { align: "right" });
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 116, 139);
  doc.setFontSize(7);
  if (brandInput?.tagline) doc.text(brand.tagline, 78, 42);
  doc.text(subtitle, pageWidth - 32, 41, { align: "right" });
}

function addFooter(doc: jsPDF, brandInput?: BasicPackingReportProps["brand"]) {
  const brand = resolveBrand(brandInput);
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const pageNumber = doc.getNumberOfPages();
  doc.setDrawColor(226, 232, 240);
  doc.line(32, pageHeight - 26, pageWidth - 32, pageHeight - 26);
  doc.setTextColor(100, 116, 139);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(6.5);
  doc.text(`Generated by ${brand.name}${brand.domainSuffix} Container Loading Calculator`, 32, pageHeight - 14);
  doc.text(`Page ${pageNumber}`, pageWidth - 32, pageHeight - 14, { align: "right" });
}

export async function generateBasicPackingReportBlob({
  containerSpec,
  cargoItems,
  result,
  totalContainers,
  unitSystem,
  containerPlans,
  brand,
}: BasicPackingReportProps): Promise<Blob> {
  const doc = new jsPDF({ unit: "pt", format: "a4", compress: true });
  const metric = unitSystem === "metric";
  const dim = (value: number) => metric ? `${(value * IN_TO_CM).toFixed(1)} cm` : `${value.toFixed(1)} in`;
  const weight = (value: number) => metric
    ? `${Math.round(value * LB_TO_KG).toLocaleString()} kg`
    : `${Math.round(value).toLocaleString()} lbs`;
  const volume = (value: number) => metric
    ? `${(value * 0.0283168).toFixed(2)} m³`
    : `${value.toFixed(1)} ft³`;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const contentWidth = pageWidth - 64;
  const includedItems = cargoItems.filter((item) => item.included && item.quantity > 0);
  const plans = containerPlans?.length
    ? containerPlans
    : [{ label: "Container 1", containerSpec, result }];
  const totalPieces = includedItems.reduce((sum, item) => sum + item.quantity, 0);
  const loadedPieces = plans.reduce((sum, plan) => sum + plan.result.piecesLoaded, 0);
  const loadedWeight = plans.reduce((sum, plan) => sum + plan.result.totalWeight, 0);
  const payloadCapacity = plans.reduce((sum, plan) => sum + plan.result.maxPayload, 0);
  const loadedVolume = plans.reduce((sum, plan) => sum + plan.result.totalVolume, 0);
  const volumeCapacity = plans.reduce((sum, plan) => sum + plan.result.containerVolume, 0);
  const balance = calculateContainerBalance(result.placed, containerSpec);

  addHeader(doc, "Container Loading Report", new Date().toLocaleString(), brand);

  let y = 86;
  doc.setTextColor(22, 163, 74);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("Container Summary", 32, y);
  y += 10;

  const summary = [
    ["Equipment", `${plans.length} container${plans.length === 1 ? "" : "s"}`],
    ["Pieces assigned", `${loadedPieces} / ${totalPieces}`],
    ["Payload used", `${payloadCapacity > 0 ? (loadedWeight / payloadCapacity * 100).toFixed(1) : "0.0"}%`],
    ["Volume used", `${volumeCapacity > 0 ? (loadedVolume / volumeCapacity * 100).toFixed(1) : "0.0"}%`],
  ];
  const boxGap = 7;
  const boxWidth = (contentWidth - boxGap * 3) / 4;
  summary.forEach(([label, value], index) => {
    const x = 32 + index * (boxWidth + boxGap);
    doc.setFillColor(241, 245, 249);
    doc.roundedRect(x, y, boxWidth, 48, 4, 4, "F");
    doc.setTextColor(100, 116, 139);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(6.5);
    doc.text(label.toUpperCase(), x + 7, y + 13);
    doc.setTextColor(15, 23, 42);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9.5);
    doc.text(value, x + 7, y + 30, { maxWidth: boxWidth - 14 });
  });
  y += 62;

  doc.setTextColor(51, 65, 85);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.text(
    `${Array.from(new Set(plans.map((plan) => plan.containerSpec.name))).join(", ")}  |  ${weight(loadedWeight)} loaded  |  ${volume(loadedVolume)}`,
    32,
    y,
  );
  y += 20;

  if (totalContainers > 1) {
    doc.setFillColor(254, 243, 199);
    doc.roundedRect(32, y - 10, contentWidth, 22, 3, 3, "F");
    doc.setTextColor(146, 64, 14);
    doc.setFont("helvetica", "bold");
    doc.text(`${totalContainers} containers required for the complete load`, 40, y + 4);
    y += 24;
  }

  doc.setTextColor(22, 163, 74);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("Weight Balance", 32, y);
  y += 9;
  const balanceColor = balance.status === "balanced"
    ? [220, 252, 231] as const
    : balance.status === "caution"
      ? [254, 243, 199] as const
      : [255, 228, 230] as const;
  const balanceLabel = balance.status === "balanced"
    ? "Well balanced"
    : balance.status === "caution"
      ? "Balance caution"
      : balance.status === "review"
        ? "Review balance"
        : "No weight data";
  doc.setFillColor(balanceColor[0], balanceColor[1], balanceColor[2]);
  doc.roundedRect(32, y, contentWidth, 34, 4, 4, "F");
  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.text(balanceLabel, 40, y + 14);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(71, 85, 105);
  doc.setFontSize(7);
  doc.text(`CG from closed end: ${dim(balance.centerXIn)} (${balance.longitudinalPct.toFixed(0)}%)`, 145, y + 14);
  doc.text(`From Side A: ${dim(balance.centerZIn)} (${balance.lateralPct.toFixed(0)}%)`, 315, y + 14);
  doc.text(`End split: ${balance.closedEndWeightPct.toFixed(0)} / ${balance.doorEndWeightPct.toFixed(0)}%`, pageWidth - 40, y + 14, { align: "right" });
  if (balance.guidance.length > 0) {
    doc.setFontSize(6.5);
    doc.text(balance.guidance.join(" "), 40, y + 26, { maxWidth: contentWidth - 16 });
  }
  y += 48;

  const drawManifestHeader = () => {
    doc.setFillColor(15, 23, 42);
    doc.rect(32, y, contentWidth, 20, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(6.5);
    doc.text("ITEM", 39, y + 13);
    doc.text("QTY", 248, y + 13, { align: "center" });
    doc.text("DIMENSIONS", 305, y + 13, { align: "center" });
    doc.text("TOTAL WEIGHT", 420, y + 13, { align: "right" });
    doc.text("STACK", pageWidth - 39, y + 13, { align: "right" });
    y += 20;
  };

  doc.setTextColor(22, 163, 74);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("Cargo Manifest", 32, y);
  y += 8;
  drawManifestHeader();

  for (let index = 0; index < includedItems.length; index += 1) {
    const item = includedItems[index];
    if (y > pageHeight - 60) {
      addFooter(doc, brand);
      doc.addPage();
      addHeader(doc, "Container Loading Report", "Cargo manifest continued", brand);
      y = 84;
      drawManifestHeader();
    }
    if (index % 2 === 1) {
      doc.setFillColor(248, 250, 252);
      doc.rect(32, y, contentWidth, 19, "F");
    }
    doc.setTextColor(51, 65, 85);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(6.8);
    doc.text((item.name || `Item ${index + 1}`).slice(0, 38), 39, y + 13);
    doc.text(String(item.quantity), 248, y + 13, { align: "center" });
    doc.text(`${dim(item.length)} × ${dim(item.width)} × ${dim(item.height)}`, 305, y + 13, { align: "center" });
    doc.text(weight(item.weight), 420, y + 13, { align: "right" });
    doc.text(item.stackable ? "Yes" : "No", pageWidth - 39, y + 13, { align: "right" });
    doc.setDrawColor(226, 232, 240);
    doc.line(32, y + 19, pageWidth - 32, y + 19);
    y += 19;
  }

  addFooter(doc, brand);

  plans.forEach((plan, planIndex) => {
  const containerSpec = plan.containerSpec;
  const result = plan.result;
  const balance = calculateContainerBalance(result.placed, containerSpec);
  doc.addPage();
  addHeader(doc, `Container ${planIndex + 1} of ${plans.length}`, `${plan.label} - ${containerSpec.name}`, brand);

  doc.setTextColor(22, 163, 74);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("Cargo placement - top view", 32, 88);

  const planX = 40;
  const planY = 108;
  const maxPlanWidth = pageWidth - 80;
  const maxPlanHeight = 360;
  const scale = Math.min(maxPlanWidth / containerSpec.lengthIn, maxPlanHeight / containerSpec.widthIn);
  const planWidth = containerSpec.lengthIn * scale;
  const planHeight = containerSpec.widthIn * scale;

  doc.setFillColor(226, 232, 240);
  doc.setDrawColor(51, 65, 85);
  doc.setLineWidth(1.2);
  doc.roundedRect(planX, planY, planWidth, planHeight, 2, 2, "FD");

  result.placed.forEach((box, index) => {
    const [red, green, blue] = hexToRgb(box.color);
    doc.setFillColor(red, green, blue);
    doc.setDrawColor(255, 255, 255);
    doc.setLineWidth(0.5);
    doc.roundedRect(
      planX + box.x * scale + 0.5,
      planY + box.z * scale + 0.5,
      Math.max(1, box.l * scale - 1),
      Math.max(1, box.w * scale - 1),
      1,
      1,
      "FD",
    );
    if (box.l * scale > 20 && box.w * scale > 12) {
      doc.setTextColor(255, 255, 255);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(6);
      doc.text(
        String(index + 1),
        planX + (box.x + box.l / 2) * scale,
        planY + (box.z + box.w / 2) * scale + 2,
        { align: "center" },
      );
    }
  });

  const cgX = planX + balance.centerXIn * scale;
  const cgY = planY + balance.centerZIn * scale;
  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(15, 23, 42);
  doc.setLineWidth(1.2);
  doc.circle(cgX, cgY, 5, "FD");
  doc.setFillColor(15, 127, 229);
  doc.circle(cgX, cgY, 1.8, "F");

  doc.setDrawColor(15, 127, 229);
  doc.setLineWidth(1.5);
  doc.setLineDashPattern([4, 3], 0);
  doc.line(planX + planWidth, planY, planX + planWidth, planY + planHeight);
  doc.setLineDashPattern([], 0);

  const noteY = planY + planHeight + 28;
  doc.setTextColor(71, 85, 105);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text(`Loaded pieces: ${result.piecesLoaded} of ${result.piecesTotal}`, 40, noteY);
  doc.text("Dashed blue line: container doors", pageWidth - 40, noteY, { align: "right" });

  doc.setTextColor(148, 163, 184);
  doc.setFontSize(6.5);
  doc.text(
    "Estimates only. Verify the final packing plan, securement, axle limits, and handling requirements with the carrier or warehouse operator before loading.",
    40,
    noteY + 28,
    { maxWidth: pageWidth - 80, align: "center" },
  );

  addFooter(doc, brand);
  });
  return doc.output("blob");
}
