-- Migration: add audit_events table for compliance-grade admin audit trail.
--
-- This file was generated by `drizzle-kit generate`, then hand-trimmed to only
-- the NEW objects added in this change (audit_events table + its FKs + indexes).
-- The original generator emitted a full schema baseline (all 21 tables) because
-- there was no prior migration history. Production already has every other
-- table, so this trimmed version is what Alex should review and apply.
--
-- Alex's deploy flow uses `npm run db:push` (drizzle-kit push), which diffs the
-- schema against the live DB and applies only the delta — meaning Alex does not
-- need to execute this SQL by hand. It is preserved here as the canonical,
-- reviewable record of what `db:push` will perform. If Alex prefers to apply
-- it manually, the statements below are idempotent-safe in the sense that they
-- only CREATE new objects (no destructive ALTER/DROP).
--
-- IF YOU ARE READING THIS BEFORE PUSHING:
--   1. Confirm `audit_events` does NOT already exist in prod.
--   2. Run `npm run db:push` (recommended) OR execute the statements below.
--   3. Verify with `\d audit_events` in psql.

CREATE TABLE "audit_events" (
	"id" serial PRIMARY KEY NOT NULL,
	"order_id" text NOT NULL,
	"actor_id" integer,
	"actor_email" text,
	"action" text NOT NULL,
	"field_name" text,
	"old_value" text,
	"new_value" text,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "audit_events" ADD CONSTRAINT "audit_events_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "audit_events" ADD CONSTRAINT "audit_events_actor_id_admin_users_id_fk" FOREIGN KEY ("actor_id") REFERENCES "public"."admin_users"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
CREATE INDEX "idx_audit_events_order_id" ON "audit_events" USING btree ("order_id");
--> statement-breakpoint
CREATE INDEX "idx_audit_events_created_at" ON "audit_events" USING btree ("created_at");
